spring:
  datasource:
    url: jdbc:postgresql://roundhouse.proxy.rlwy.net:27471/railway
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      properties:
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
